version: '3.9'
services:
  postgres:
    image: debezium/postgres:14-alpine
    container_name: postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - pg_volume:/var/lib/postgresql/data
volumes:
  pg_volume:
    driver: local
