name: Dispatch GraphQL Schema Update

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS: .*/**/schema.graphql
      - name: Dispatch update-graphql-schema
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: EduardValentin/graphql-mesh-poc-client
          token: ${{ secrets.POC_GRAPHQL_MESH_ACCESS_TOKEN }}
          event-type: update-graphql-schema
        if: env.GIT_DIFF