sources:
  - name: sword-api
    handler:
      grpc:
        endpoint: localhost:50051
        source:
          file: ../proto/src/main/proto/com/sword/v1/sword_service.proto
          load:
            includeDirs:
              - ../proto/src/main/proto
  - name: samurai-api
    handler:
      grpc:
        endpoint: localhost:50052
        source:
          file: ../proto/src/main/proto/com/samurai/v1/samurai_service.proto
          load:
            includeDirs:
              - ../proto/src/main/proto

transforms:
  - namingConvention:
      typeNames: camelCase
      fieldNames: camelCase
      fieldArgumentNames: camelCase
  - rename:
      renames:
        - from:
            field: comSword
            type: Mutation
          to:
            field: api
            type: Mutation
          useRegExpForTypes: true
          useRegExpForFields: true
        - from:
            field: comSword
            type: Query
          to:
            field: api
            type: Query
          useRegExpForTypes: true
          useRegExpForFields: true
        - from:
            type: comSword
          to:
            type: ""
          useRegExpForTypes: true
        - from:
            type: comSamurai
          to:
            type: ""
          useRegExpForTypes: true

additionalTypeDefs: |
  extend type com_samurai_v1_Samurai {
    swords: [com_sword_v1_Sword]
  }
  extend type com_sword_v1_Sword {
    samurai: com_samurai_v1_Samurai 
  }

additionalResolvers:
  - "./resolvers.ts"
